# Sponsorship supports maintenance of the MOBIUS open-source stack.
# It grants no license and no support entitlement. The code is
# AGPL-3.0-or-later; a commercial license (relief from AGPL copyleft)
# is a separate paid product — see the README or info@mobius.style.
github: [mobius-style]
